### ISSUE TITLE
Cross-site Scripting issue

### ISSUE THREAD

**Issue by ghost** [telephone/LookingGlass#18]
Hi mate!

Your app suffer from a Cross-site Scripting (XSS) issue. 
File: index.php 
Line: 62 
Vuln:

<h1><a id="title" href="<?php echo $_SERVER['REQUEST_URI']; ?>"><?php echo $siteName; ?></a></h1>

You should clean the inputs prior to print them to screen. 

Cheers!

**Comment by telephone** [comment]
Fixed in bbfb2ea
