### ISSUE TITLE
Configuration variable/s missing.

### ISSUE THREAD

**Issue by MLWALK3R** [telephone/LookingGlass#27]
Just pulled the latest version and reinstalled it, Keep getting "Configuration variable/s missing. Please run configure.sh" I've done the configure.sh setup.

**Comment by telephone** [comment]
v1.3.0 adds a new variable `$siteUrl` to `LookingGlass/Config.php`. If you haven't run `bash configure.sh` after your update, then there's your problem.

^ I just tested again by installing v1.2.0 (running configure), and then updating to v1.3.0 (re-running configure). Everything works how it should.

**Comment by MLWALK3R** [comment]
Weird I haven't touched it since I opened this issue and it seems to be working http://lg.walk3r.com/

**Comment by telephone** [comment]
A note for the future:

This was likely caused by OPcache serving a cached version of `Config.php`. When the timer was up, or the file was revalidated it was updated accordingly.
