### ISSUE TITLE
Please add paping as an option

### ISSUE THREAD

**Issue by GTAXL** [telephone/LookingGlass#28]
I would appreciate it if you added paping as an option to your looking glass, as not everything replies to icmp and being able to ping a TCP port is very handy. You can find it here, you just download a single executable it's really easy. https://code.google.com/p/paping/

**Comment by telephone** [comment]
I won't be adding `paping` as a default option for the following reasons:
- The project appears abandoned. No release in 4 years
- Not in Debian/Ubuntu packages
- There appears to be no IPv6 support
- If `ping` is not allowed, `traceroute` and `mtr` are available

If you would like to replace `ping` with `paping` in v1, then change the `ping` command in `LookingGlass.php`

(v2 will allow for custom commands in a more straight-forward approach)
