### ISSUE TITLE
Ping / MTR not working

### ISSUE THREAD

**Issue by s4m4n** [telephone/LookingGlass#32]
I just installed the LookingGlass for testing and noticed that MTR and ping are not working, Host and Traceroute are working fine. I tried making changes to Ping function to below:

return $this->procExecute('ping --help', $host);

It didn't returned anything either. null reponse.

Also, file permissions are fine and there is no error log.

Any idea?

**Comment by telephone** [comment]
What OS?

The problem is permission (SUID) based. The short of it is ping and MTR need root permission to open a socket, but some OS' have tighter privileges which prevent your web user (www-user) from accessing the commands.

Try these commands:

```bash
sudo chmod u+s `which ping`
sudo chmod u+s `which mtr`
```

**Comment by s4m4n** [comment]
Well, It was SElinux :) Thanks
