### ISSUE TITLE
RateLimit appears not to be working

### ISSUE THREAD

**Issue by paradoxni** [telephone/LookingGlass#34]
I have LG installed on Ubuntu 14.04, Nginx and using PHP FPM. 

All is working apart from the rate limiting does not seem to take effect. The SQL lite database does not appear to be filling with data. No errors are reported in the error log.

ii  php5-common                         5.5.9+dfsg-1ubuntu4.14        amd64        Common files for packages built from the php5 source
ii  php5-fpm                            5.5.9+dfsg-1ubuntu4.14        amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php5-json                           1.3.2-2build1                 amd64        JSON module for php5
ii  php5-mysql                          5.5.9+dfsg-1ubuntu4.14        amd64        MySQL module for php5
ii  php5-sqlite                         5.5.9+dfsg-1ubuntu4.14        amd64        SQLite module for php5

**Comment by telephone** [comment]
I just tested locally on a new install (PHP 5.6) and the rate limit does work. My guess is your web server does not have permission to write to the SQLite file (if your SQLite has no data).

The configure script changes the owner of `ratelimit.db` to ensure it's writeable. If this step failed, then you'll need to do this manually.

**Comment by paradoxni** [comment]
Thanks for replying.

Nginx and FPM run as www-data, which the SQLite DB is owned and writeable by. I will enabled debug logging on both and do some more tests. The issue clearly is with the server, but if you can think of anything else to try I would appreciate it.

Thanks again.
