### ISSUE TITLE
apache LG

### ISSUE THREAD

**Issue by kotviphp** [telephone/LookingGlass#55]
Help configure Apache for LG, installed a script, I can not start the web

Unable to access the site The web page at https://localhost/ may be temporarily unavailable or constantly moved to a new address.
ERR_TUNNEL_CONNECTION_FAILED

**Comment by Wild1145** [comment]
Would generally suggest against using localhost, a lot of browsers no longer allow HTTPS to work with it, should probably host it on a proper domain I'd suggest.

**Comment by kotviphp** [comment]
Thanks!
