### ISSUE TITLE
change port

### ISSUE THREAD

**Issue by kotviphp** [telephone/LookingGlass#56]
default port is 80, how to change port?

**Comment by Wild1145** [comment]
The app doesn't listen on any specific port from memory, it just runs on the Apache / NginX web server. Here's a guide on how to change it in Apache, hopefully that helps - https://www.tecmint.com/change-apache-port-in-linux/

**Comment by kotviphp** [comment]
Thanks!,

**Comment by kotviphp** [comment]
it's work
https://www.tecmint.com/change-apache-port-in-linux/
